### ISSUE TITLE
Main dapp tutorial should be written using the new dapp kit and veworld

### ISSUE THREAD

**Issue by davidecarpini** [vechain/vechain-docs#11]
link to the tutorial:
https://docs.vechain.org/start-building/tutorials/how-to-develop-a-dapp-on-vechain/how-to-develop-a-dapp-on-vechain-i-intro

**Comment by nwbrettski** [comment]
Completely agree this content is outdated and requires a rewrite given the existence of the dApp-kit. Feel free to make a PR.

**Comment by nwbrettski** [comment]
Given that this content has been removed via this [PR](https://github.com/vechain/vechain-docs/pull/30) a new tutorial should be created with the latest tools, dapp-kit and veworld.

**Comment by fabiorigam** [comment]
@ifavo wrote a tutorial using dApp kit, so we can close this one. Please open another issue if you have suggestions for a new tutorial.
