### ISSUE TITLE
Change the doc title

### ISSUE THREAD

**Issue by davidecarpini** [vechain/vechain-docs#12]
- as a developer, I expect to find a 'Getting Started' section as the first tab of the menu
- we should separate developer sections from general-purpose sections
- 'Welcome to vechain - blockchain for our better world' can't be a menu item title, it's too long

<img width="1724" alt="Screenshot 2023-12-11 at 15 41 33" src="https://github.com/vechainfoundation/vechain-docs/assets/5785838/52ee4dc3-e22e-47c4-a7d8-586878110c20">
<img width="1723" alt="Screenshot 2023-12-11 at 15 41 44" src="https://github.com/vechainfoundation/vechain-docs/assets/5785838/2ee44835-d8f4-4d47-a186-31188ecbeb04">
<img width="1709" alt="Screenshot 2023-12-11 at 15 54 44" src="https://github.com/vechainfoundation/vechain-docs/assets/5785838/e31fb4a4-c9dc-41dc-b5b4-75f3ffe638a8">
<img width="1726" alt="Screenshot 2023-12-11 at 15 40 45" src="https://github.com/vechainfoundation/vechain-docs/assets/5785838/a5bab301-e2a0-45ad-8f3f-25a10c8ab3b9">

**Comment by nwbrettski** [comment]
@davidecarpini 

- In terms of separation for a developer to non-developer this is present, `Developer Resources` is a section entirely aimed at developers same with the `Start Building` section. What would your alternative suggestion be?
- Feel free to make a PR to change the title it can be shorted to be `Welcome to vechain`

**Comment by fabiorigam** [comment]
Done
