### ISSUE TITLE
Collect 404 and create redirects

### ISSUE THREAD

**Issue by fabiofvc** [vechain/vechain-docs#15]
**Problem:**
Listening @nwbrettski I hear a story.
This doc lived some reorgs, leading to some URL changes + 404 HTTP errors.
This could lead to bad SEO or user experience.

**Solution:**
- If we use third-party integrations we may collect 404 pages (Google Analytics or similar are available) - https://docs.gitbook.com/integrations/third-party-integrations
- We could create a YAML file with redirects - https://docs.gitbook.com/integrations/git-sync/content-configuration#redirects

In this way, reorg could be easier and more frequent (if we need it).

**Comment by fabiorigam** [comment]
Will reopen if this issue arises again, not needed now imo.
